### ISSUE TITLE
Add @ipld/dag-json encoder by default

### ISSUE THREAD

**Issue by hacdias** [nftstorage/carbites#16]
Hi! It would be great if [`@ipld/dag-json`](https://www.npmjs.com/package/@ipld/dag-json) was added by default on the encoders list, just like raw and cbor are. `dag-json` should be a first-class citizen in IPFS 😃

**Comment by alanshaw** [comment]
🙏 I would definitely accept a PR

Note that web3.storage and nft.storage are moving towards a "simple" splitter approach where we don't have to decode blocks to be able to store them. This is way more future proof.

**Comment by hacdias** [comment]
@alanshaw that is very nice to hear! Is it then worth it adding the `dag-json` here?

**Comment by alanshaw** [comment]
I think it's worth adding in the mean time (we're a few months out) and also for anyone using this library for other purposes.

**Comment by hacdias** [comment]
@alanshaw done: #17
