### ISSUE TITLE
Error: Cannot find module 'carbites/treewalk'

### ISSUE THREAD

**Issue by shreyassai123** [nftstorage/carbites#4]
Receiving this error whenever I'm trying to import 'carbites/treewalk' into my JavaScript File.

**Comment by alanshaw** [comment]
Please can you post some sample code that demonstrates the problem?

**Comment by shreyassai123** [comment]
`import { TreewalkCarSplitter } from 'carbites/treewalk'`

**Comment by alanshaw** [comment]
This works fine for me in Node.js 16 and 14, I'm going to need some more information. Have you installed the module? I'm assuming you're using Node.js - what version please? What version of carbites are you trying to import? Have you tried upgrading to the latest version?

**Comment by dchoi27** [comment]
Closing for now, reopen if this is still an issue!
