### ISSUE TITLE
Error: Cannot find module 'carbites/treewalk'

### ISSUE THREAD

**Issue by azpublic** [nftstorage/carbites#7]
Hi ! 
I just installed nft.storage and tried the example provided but I'm getting an error when trying to run it : 

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'carbites/treewalk'

Node version  12.3.1
running on windows ... 

very barebones project with just nft storage installed 

Thanks for any help.

**Comment by dchoi27** [comment]
@hugomrdias any thoughts (looks like you put together most of the examples for NFT.Storage)? feel free to tag in someone else too.

**Comment by hugomrdias** [comment]
Hi @azpublic can you please update your node to an active LTS version and retry please?

**Comment by dchoi27** [comment]
Hey @azpublic - let us know if this doesn't fix things. Closing for now.
